# Generated by Django 2.2.6 on 2019-11-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('ticket_number', models.IntegerField(blank=True, max_length=50)),
                ('taxi_driver', models.CharField(max_length=50)),
                ('order_time', models.DateTimeField()),
                ('order_location', models.CharField(max_length=50)),
            ],
        ),
    ]
