# Generated by Django 2.2.6 on 2019-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_reservationform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationform',
            old_name='order_location',
            new_name='from_loc',
        ),
        migrations.AddField(
            model_name='reservationform',
            name='to_loc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='ticket_number',
            field=models.IntegerField(blank=True),
        ),
    ]
