# Generated by Django 2.2.6 on 2019-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191105_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='taxi_driver',
            field=models.CharField(choices=[('max', 'MAX'), ('peter', 'PETER'), ('manu', 'MANU'), ('sebastian', 'SEBASTIAN'), ('donald', 'DONALD')], default='max', max_length=50),
        ),
    ]
