# Generated by Django 2.2.6 on 2019-11-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20191105_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='order_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='taxi_driver',
            field=models.CharField(choices=[('max', 'Max'), ('peter', 'Peter'), ('manu', 'Manu'), ('sebastian', 'Sebastian'), ('donald', 'Donald')], default='max', max_length=50),
        ),
    ]
