# Generated by Django 2.2.6 on 2019-11-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20191105_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='order_time',
            field=models.DateTimeField(),
        ),
    ]
