# Generated by Django 2.2.6 on 2019-11-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20191105_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
