# Generated by Django 2.2.6 on 2019-11-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20191105_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='order_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
