# Generated by Django 2.2.6 on 2019-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20191105_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='title',
            field=models.CharField(blank=True, choices=[('1person', '1 Person'), ('2person', '2 Personen'), ('3person', '3 Personen'), ('4person', '4 Personen'), ('5person', '5 Personen'), ('6person', '6 Perosnen')], max_length=50),
        ),
    ]
