# Generated by Django 2.2.6 on 2019-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20191105_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='taxi_driver',
            field=models.CharField(choices=[('max', 'Max'), ('peter', 'Peter'), ('manu', 'Manu'), ('sebastian', 'Sebastian'), ('donald', 'Donald')], max_length=50),
        ),
    ]
