# Generated by Django 2.2.6 on 2019-11-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20191105_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationform',
            name='from_plz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationform',
            name='from_street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservationform',
            name='from_street_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservationform',
            name='to_plz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationform',
            name='to_street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservationform',
            name='to_street_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='from_loc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='title',
            field=models.CharField(blank=True, choices=[('1person', '1 Person'), ('2person', '2 Personen'), ('3person', '3 Personen'), ('4person', '4 Personen'), ('5person', '5 Personen'), ('6person', '6 Personen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='to_loc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
