# Generated by Django 2.2.6 on 2019-11-06 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_reservationform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='title',
            field=models.CharField(blank=True, choices=[('1person', '1 Person'), ('2personen', '2 Personen'), ('3personen', '3 Personen'), ('4personen', '4 Personen'), ('5personen', '5 Personen'), ('6personen', '6 Personen')], max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
