# Generated by Django 2.2.6 on 2019-11-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20191106_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_from_my_db',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
