# Generated by Django 2.2.6 on 2019-11-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_user_from_my_db_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
